### ISSUE TITLE
On click of the widget the a pop up should show up

### ISSUE THREAD

**Issue by daveRanjan** [daveRanjan/doordashan#3]

**Comment by monis001** [comment]
Is there any mechanism to add widget already? or do we have to consider that first?

**Comment by monis001** [comment]
I believe with the current state we can just open up the popup as for now, but what content to be there can be decided while deciding configuration items. @daveRanjan your thoughts on this ?

**Comment by monis001** [comment]
https://github.com/daveRanjan/doordashan/pull/14
@daveRanjan
